import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  instagramConversations: defineTable({
    agentReplied: v.boolean(),
    agentReplyAt: v.optional(v.float64()),
    agentReplyText: v.optional(v.string()),
    claimExpiresAt: v.optional(v.float64()),
    claimToken: v.optional(v.string()),
    claimedAt: v.optional(v.float64()),
    contactId: v.string(),
    igFollowersCount: v.optional(v.float64()),
    igMessagingWindow: v.optional(v.string()),
    instagramAccountName: v.optional(v.string()),
    instagramUserId: v.optional(v.string()),
    isIgAccountFollowUser: v.optional(v.boolean()),
    isIgAccountFollower: v.optional(v.boolean()),
    isIgVerifiedUser: v.optional(v.boolean()),
    lastIgInteraction: v.optional(v.string()),
    lastIgSeen: v.optional(v.string()),
    lastReplyType: v.optional(v.string()),
    message: v.optional(v.string()),
    name: v.optional(v.string()),
    optinInstagram: v.optional(v.boolean()),
    rawPayload: v.optional(v.any()),
    receivedAt: v.float64(),
  })
    .index("by_agent_replied", ["agentReplied"])
    .index("by_contact_id", ["contactId"])
    .index("by_instagram_user_id", ["instagramUserId"]),
  signal_conversations: defineTable({
    contactId: v.string(),
    createdAt: v.float64(),
    lastMessageAt: v.optional(v.float64()),
    messageCount: v.optional(v.float64()),
    messages: v.optional(v.any()),
  }).index("by_contact_id", ["contactId"]),
  signal_daily_digest: defineTable({
    createdAt: v.float64(),
    date: v.string(),
    followUpsSent: v.optional(v.float64()),
    hotLeads: v.optional(v.float64()),
    newLeads: v.optional(v.float64()),
    topIntents: v.optional(v.any()),
    totalMessages: v.optional(v.float64()),
  }).index("by_date", ["date"]),
  signal_followups: defineTable({
    contactId: v.string(),
    createdAt: v.float64(),
    followUpCount: v.optional(v.float64()),
    lastAgentReply: v.optional(v.string()),
    lastUserMessage: v.optional(v.string()),
    pendingSince: v.optional(v.float64()),
    status: v.optional(v.string()),
  }).index("by_contact_id", ["contactId"]),
  signal_leads: defineTable({
    contactId: v.string(),
    createdAt: v.float64(),
    intent: v.optional(v.string()),
    lastInteraction: v.optional(v.float64()),
    messageCount: v.optional(v.float64()),
    name: v.optional(v.string()),
    score: v.optional(v.float64()),
    stage: v.optional(v.string()),
    status: v.optional(v.string()),
    updatedAt: v.optional(v.float64()),
  }).index("by_contact_id", ["contactId"]),
});
